builders:
  entity:
    import: "package:flutter_persistence_firestore/builder.dart"
    builder_factories: ["entityBuilder"]
    build_extensions: {".dart": [".model.dart"]}
    auto_apply: dependents
    build_to: source