builders:
  entity:
    import: "package:flutter_persistence_firestore/builder.dart"
    builder_factories: ["entityBuilder"]
    build_extensions: {".dart": [".entity.dart"]}
    auto_apply: dependents
    build_to: source

  repository:
    import: "package:flutter_persistence_firestore/builder.dart"
    builder_factories: ["repositoryBuilder"]
    build_extensions: {".dart": [".entity.dart"]}
    auto_apply: dependents
    build_to: source