name: flutter_persistence_firestore
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.2+1
  build: ^1.2.2
  source_gen: ^0.9.4+6
  flutter_persistence_api:
    path: ../flutter_persistence_api
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
